Npascuas pokeball
yum-feng/COMP5541TeamZombieCode pull request #11
Opened 2022-02-20 17:20 UTC by npascuas

2022-02-23 04:51 UTC, acpears commented
Just a suggestion but since we are defining 3 types of pokeballs, should the naming of each start with the colour. I currently see as naming convention pokeball, green_pokeball, blue_pokeball. Maybe change pokeball to red_pokeball as i believe it is the red one.

2022-02-23 05:00 UTC, acpears requested changes

2022-02-23 05:00 UTC, acpears commented on src/main/java/teamzombie/pokez/setup/Registration.java
> +	public static final RegistryObject<Item> Pokeball = ITEMS.register("pokeball", () -> new PokeballItem());
Can we seperate the pokeball registrations from the animal item registrations with a comment just for clean code purposes

2022-02-26 01:07 UTC, npascuas reviewed
Done

2022-02-26 01:07 UTC, closed without merging