Acpears poke animal items
yum-feng/COMP5541TeamZombieCode pull request #5
Opened 2022-02-13 21:53 UTC by acpears

I have added a basic folder and file structure as well as the datageneration folder used to create the JSON files. Please review the structure and let me know if you see any  issues.

2022-02-13 22:41 UTC, mikepoullas requested changes
Going forward, try to remove all unused imports. 
In eclipse, it shows several of them are not required.
Also, if vars, objects or code is not being used remove it completely 
instead of applying comments. Thank you!

2022-02-13 23:23 UTC, yum-feng commented
> Going forward, try to remove all unused imports. In eclipse, it shows several of them are not required. Also, if vars, objects or code is not being used remove it completely instead of applying comments. Thank you!

A static code analysis tool should be able to catch unused imports. Would be interesting if one of the testers looked into setting one up.

2022-02-13 23:54 UTC, acpears commented
@mikepoullas i have made the changes.. this should be ready to merge

2022-02-14 01:57 UTC, mikepoullas approved these changes

2022-02-18 03:14 UTC, merged